<?php

namespace Richpolis\BackendBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ConfiguracionesesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConfiguracionesRepository extends EntityRepository
{
    public function getMaxPosicion(){
        $em=$this->getEntityManager();
        $query=$em->createQuery('
            SELECT MAX(p.id) as value 
            FROM BackendBundle:Configuraciones p
            ');
        $max=$query->getResult();
        return $max[0]['value'];
    }
    
    public function getQueryConfiguracionesActivas($todas=false){
        $query=$this->createQueryBuilder('p')
                    ->orderBy('p.configuracion', 'ASC');
        return $query->getQuery();
    }
    
    public function getConfiguracionesActivas($todas=false){
        $query=$this->getQueryConfiguracionesActivas($todas);
        return $query->getResult();
    }
    
    
}